### PR TITLE
Update to Swift 4 and Kitura-net 2.0

### PR DESCRIPTION
**Pull request by AnthonyOliveri**

### CODE REVIEW

**Comment by tunniclm** [comment]
@AnthonyOliveri - It looks like the most recent build failed on `swift build --clean` because in Swift 4 the `swift` command has changed. The new command to do this is `swift package clean`

**Comment by AnthonyOliveri** [comment]
Thanks for catching that. There's no real need for the `swift build --clean` (since Travis builds start from scratch) and I removed the `swift package fetch` as well since that's taken care of in `swift build`.

**Comment by AnthonyOliveri** [comment]
@tunniclm Can you review and approve this so we can merge it?

**Comment by tunniclm** [comment]
Ah, it looks like you need someone with write access to review this.

**Pull request merged**
